// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ptud_project.Data;

namespace ptud_project.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ptud_project.Data.Customer", b =>
                {
                    b.Property<Guid>("id_cus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cmnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("created_at")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<short>("sex")
                        .HasMaxLength(2)
                        .HasColumnType("smallint");

                    b.Property<long>("update_at")
                        .HasColumnType("bigint");

                    b.HasKey("id_cus");

                    b.HasIndex("phone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ptud_project.Data.Provider", b =>
                {
                    b.Property<Guid>("id_prov")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("owner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<short>("rating")
                        .HasColumnType("smallint");

                    b.HasKey("id_prov");

                    b.HasIndex("owner");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("ptud_project.Data.Provider", b =>
                {
                    b.HasOne("ptud_project.Data.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("owner");

                    b.Navigation("customer");
                });
#pragma warning restore 612, 618
        }
    }
}
